Base:
    model_root: './checkpoints/'
    num_workers: 1
    verbose: 1
    early_stop_patience: 2
    pickle_feature_encoder: True
    save_best_only: True
    eval_steps: null
    debug_mode: False
    group_id: null
    use_features: null
    feature_specs: null
    feature_config: null

DCN_MEMONETV3_test:
    model: DCN_MEMONETV3
    dataset_id: KKBox_x1
    fields_num: 19
    use_kif: True
    n_rows : 300000
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.0005
    net_regularizer: 0
    batch_size: 10000
    embedding_dim: 20
    mid_dim : 20
    dnn_hidden_units: [1000, 1000]
    dnn_activations: relu
    crossing_layers: 3
    net_dropout: 0.4
    batch_norm: False
    epochs: 30
    shuffle: True
    seed: 2019
    monitor: 'AUC'
    monitor_mode: 'max'